### ISSUE TITLE
Getting Syslog error in maas-regional-controller 

### ISSUE THREAD

**Issue by snivas** [att-comdev/dockerfiles#72]
Sorry for putting it under issues :(

I am getting "ValueError: Unable to configure handler 'syslog': [Errno 2] No such file or directory". Have you enoucntered such issue before while running a maas-regional-controller with image built using the Docker file in this repo? my docker version is  (Version: 1.12.5)

Traceback (most recent call last):
  File "/usr/bin/twistd3", line 18, in <module>
    run()
  File "/usr/lib/python3/dist-packages/twisted/scripts/twistd.py", line 29, in run
    app.run(runApp, ServerOptions)
  File "/usr/lib/python3/dist-packages/twisted/application/app.py", line 617, in run
    runApp(config)
  File "/usr/lib/python3/dist-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python3/dist-packages/twisted/application/app.py", line 348, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python3/dist-packages/twisted/application/app.py", line 408, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
  File "/usr/lib/python3/dist-packages/maasserver/plugin.py", line 109, in makeService
    self._configureLogging(options["verbosity"])
  File "/usr/lib/python3/dist-packages/maasserver/plugin.py", line 50, in _configureLogging
    logger.configure(verbosity, logger.LoggingMode.TWISTD)
  File "/usr/lib/python3/dist-packages/provisioningserver/logger/__init__.py", line 122, in configure
    configurator(verbosity, mode)
  File "/usr/lib/python3/dist-packages/provisioningserver/logger/_logging.py", line 59, in configure_standard_logging
    set_standard_verbosity(verbosity)
  File "/usr/lib/python3/dist-packages/provisioningserver/logger/_logging.py", line 43, in set_standard_verbosity
    logging.config.dictConfig(get_logging_config(verbosity))
  File "/usr/lib/python3.5/logging/config.py", line 795, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.5/logging/config.py", line 566, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'syslog': [Errno 2] No such file or directory

Thanks,
Nivas

**Comment by snivas** [comment]
/usr/sbin/rsyslogd was not running it seems. Once it started. It is working now.

Thanks
